stages:
  - test
  - package

lint-lua-code:
  stage: test
  tags:
    - cops-and-robbers
  # This new line tells GitLab not to fail the pipeline because of warnings.
  # The job will be marked as "passed with warnings" (a yellow icon).
  allow_failure: true
  script:
    - echo "Running Lua linter..."
    - luacheck .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

package-resource:
  stage: package
  tags:
    - cops-and-robbers
  script:
    - echo "Packaging resource..."
    # This command uses PowerShell's native 'Compress-Archive' to create the zip file.
    # We list all the files and directories we want to include.
    - Compress-Archive -Path "fxmanifest.lua", "*.lua", "html", "player_data", "*.json", "data" -DestinationPath "${CI_PROJECT_NAME}.zip" -Force
  artifacts:
    # The artifacts section is the same, as it's a GitLab feature.
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - "*.zip"
    expire_in: 1 week
  # This rule ensures the package job only runs on the main branch.
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'