steps:
  - label: ":lua: Lint Code"
    command: "luacheck ."
    plugins:
      - docker#v5.9.0:
          # Use the correct, valid image name
          image: "mpeterv/luacheck:latest"
    soft_fail: true

- label: ":package: Package Resource Artifacts"
    command: "buildkite-agent artifact upload '**/*'"

# The pipeline will now finish after this step.