steps:
  - label: ":lua: Lint Code"
    command: "luacheck ."
    plugins:
      - docker#v5.9.0:
          image: "lua-check/lua-check:latest"
    soft_fail: true

  - label: ":package: Package Resource Artifacts"
    command: "buildkite-agent artifact upload '**/*'"

  - wait

  - block: "Deploy to Server?"
    if: build.branch == "main"

  - label: ":rocket: Deploy"
    if: build.branch == "main"
    command: "./scripts/deploy.sh"