steps:
  - label: ":lua: Lint Code"
    command: "luacheck ."
    plugins:
      - docker#v5.9.0:
          # Use the name of your locally built image
          image: "my-luacheck:latest"
    soft_fail: true

  - label: ":package: Package Resource Artifacts"
    command: "buildkite-agent artifact upload '**/*'"